### ISSUE TITLE
Page lists values are overwritten with new request data

### ISSUE THREAD

**Issue by manoj279** [pegasystems/mashup-webcomponent#3]
Usecase:
We fetch and display a list of policies using a pagelist and allow user to select one or many policies. On submit, we fetch policy data  of the selected policy and proceed forward.

Issue:
On submit, only changed values are passed in content field of request body. And in step-16 of acquireWorkObject activity, the pagelist values are overwritten with new data passed.

Request:
![content field](https://user-images.githubusercontent.com/22269847/122158718-bc9ac380-ce8a-11eb-8b38-638bce8fb7dc.jpg)

Acquire workobject activity:
![acquireworkobject](https://user-images.githubusercontent.com/22269847/122158756-cc1a0c80-ce8a-11eb-8024-5c4d2f13cf12.jpg)

Inital policylist data
![Initail pageslist data](https://user-images.githubusercontent.com/22269847/122158918-0d122100-ce8b-11eb-9a12-1fa1085f843b.jpg)

After merge:
![After merge](https://user-images.githubusercontent.com/22269847/122158931-156a5c00-ce8b-11eb-8748-c316028ac7d0.jpg)

**Comment by ricmars** [comment]
is is using v1 or v2 DX API? I might need to change how data are sent back in the case of a table - right now only the delta is passed to the api.

**Comment by niallriddell** [comment]
Page Instructions support will be required to fix this issue I feel.

**Comment by manoj279** [comment]
We are using v1 DX API. In react starter kit, the values changed are passed in page instructions field of request payload. 
Can the urgency of this issue be increased as all our service cases use table layout and this would be a blocker for testing DX API compliance

**Comment by ricmars** [comment]
v1 and v2 implementation are now using page instructions for embedded pages and page lists.

**Comment by ricmars** [comment]
closing issue
